# Generated by Django 3.1.6 on 2021-02-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='', max_length=200, verbose_name='password2'),
            preserve_default=False,
        ),
    ]
